name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check formatting
      run: bash scripts.sh cf
    - name: Clippy
      run: bash scripts.sh cc
    - name: Run tests
      run: bash scripts.sh ct
